# Generated by Django 3.2.5 on 2021-07-22 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='真实姓名'),
        ),
    ]
