# Generated by Django 3.2.5 on 2021-07-22 05:04

from django.db import migrations, models
import user.fields
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='用户权限'),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='用户地址'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=user.fields.RestrictedFileField(default='default_avatar.jpeg', upload_to=user.models.user_directory_path, verbose_name='用户头像'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='用户国家'),
        ),
        migrations.AddField(
            model_name='user',
            name='geographic',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='用户家乡'),
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='用户部门'),
        ),
        migrations.AddField(
            model_name='user',
            name='notifyCount',
            field=models.IntegerField(blank=True, max_length=255, null=True, unique=True, verbose_name='用户通知数量'),
        ),
        migrations.AddField(
            model_name='user',
            name='signature',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='用户个性签名'),
        ),
        migrations.AddField(
            model_name='user',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='用户标签'),
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='用户称呼'),
        ),
        migrations.AddField(
            model_name='user',
            name='unreadCount',
            field=models.IntegerField(blank=True, max_length=255, null=True, unique=True, verbose_name='用户未读通知数量'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(blank=True, max_length=255, null=True, unique=True, verbose_name='用户ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='用户姓名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='用户电话号码'),
        ),
    ]
