# Generated by Django 3.2.5 on 2021-07-22 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210722_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='notifyCount',
            new_name='notify_count',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='unreadCount',
            new_name='unread_count',
        ),
    ]
