# Generated by Django 3.2.5 on 2021-07-23 13:48

from django.db import migrations, models
import user.fields
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210722_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=user.fields.RestrictedFileField(default='default_avatar.png', upload_to=user.models.user_directory_path, verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='notify_count',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='用户通知数量'),
        ),
        migrations.AlterField(
            model_name='user',
            name='unread_count',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='用户未读通知数量'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='用户ID'),
        ),
    ]
